# This is a basic workflow to help you get started with Actions

name: PR

on:
  push:

jobs:
  check-dependabot:
    runs-on: ubuntu-latest
    if: ${{ true }}
    steps:
      - run: echo "PR created by Dependabot"
